name: IP_Catalog Workflow

on:
  push:
  pull_request:

jobs:
  IP_Catalog_Ubuntu:
    runs-on: ubuntu-latest
    steps:

    - name: Cancel previous
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
        
    - name: ssh-agent
      uses: webfactory/ssh-agent@v0.5.4
      with: 
        ssh-private-key: |
          ${{ secrets.SSH_PRIVATE_KEY_RAPTOR_TOOLS }}

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Clone Raptor_Tools
      run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git submodule update --init Raptor_Tools
          ls Raptor_Tools
          exit 1
          
    - name: Install dependencies
      run: 
        sudo apt-get update
        sudo apt install -y cmake build-essential
        sudo apt install -y python3 python3-pip
        python3 -m pip install --upgrade pip
        python3 -m pip install pipenv


    - name: Show shell configuration
      run: |
        env
        which cmake && cmake --version
        which make && make --version
        which python3 && python3 --version
        pipenv --version

    - name: Create Virtual ENV
      shell: bash
      run: |
        cd Raptor_Tools/python_tools
        make build  

    - name: Test IP Generation
      run: |
        cd Raptor_Tools/python_tools/build/share/envs/litex && pipenv shell
        python3 ./RapidSilicon/IP/axi_dpram/v1_0/axi_dpram_gen.py --data_width=32 --addr_width=8 --build-name=dpram_wrapper --build
        tree ./ip_build/rapidsilicon/ip/axi_dpram/ -L 4
        python3 ./RapidSilicon/IP/axi_ram/v1_0/axi_ram_gen.py --data_width=32 --addr_width=8 --build-name=ram_wrapper --build
        tree ./ip_build/rapidsilicon/ip/axi_ram/ -L 4
        python3 ./RapidSilicon/IP/axi_register/v1_0/axi_register_gen.py --data_width=64 --addr_width=32 --build-name=register_wrapper --build
        tree ./ip_build/rapidsilicon/ip/axi_register/ -L 4
        python3 ./RapidSilicon/IP/axil_gpio/v1_0/axil_gpio_gen.py --data_width=16 --addr_width=8 --build-name=gpio_wrapper --build
        tree ./ip_build/rapidsilicon/ip/axil_gpio/ -L 4
        python3 ./RapidSilicon/IP/axil_uart/v1_0/axil_uart_gen.py --addr_width=8 --rdata_width=32 --build-name=uart_wrapper --build
        tree ./ip_build/rapidsilicon/ip/axil_uart/ -L 4

#--------------------------CentOS------------------------------------
#  centos7-gcc:
#      name:  IP_Catalog_centos
#      runs-on: ubuntu-latest
#      container:
#        image: centos:7
#      defaults:
#        run:
#          shell: bash
#      steps:
#      - name: Cancel previous
#        uses: styfle/cancel-workflow-action@0.9.1
#        with:
#          access_token: ${{ github.token }}
#
#      - name: Install GCC-9 & latest Git
#        run: |
#          yum install -y openssh-server openssh-clients
#          yum-config-manager --enable rhel-server-rhscl-7-rpms
#          yum install -y https://repo.ius.io/ius-release-el7.rpm
#          yum install -y centos-release-scl
#          yum install -y devtoolset-9
#          yum install -y devtoolset-9-toolchain
#          yum remove -y git*
#          yum install -y https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
#          yum install -y git
#
#
#      - name: Checkout code
#        uses: actions/checkout@v2
#        with:
#          submodules: recursive
#          fetch-depth: 0
#
#      - name: Install dependencies
#        run: 
#          bash .github/workflows/install_centos_dependencies_build.sh  
#          bash .github/workflows/install_litex_centos.sh
#
#
#      - name: Configure shell
#        shell: bash
#        run: |
#          source /opt/rh/devtoolset-9/enable
#          source /opt/rh/rh-python38/enable
#          PYTHON_USER_SITE=$(python3 -m site --user-site)
#          echo $PYTHON_USER_SITE
#          echo 'PYTHONPATH=$PYTHON_USER_SITE:/__w/IP_Catalog/IP_Catalog/migen:/__w/IP_Catalog/IP_Catalog/litex/'"$PYTHONPATH" >> $GITHUB_ENV
#          echo 'CC=/opt/rh/devtoolset-9/root/usr/bin/gcc' >> $GITHUB_ENV
#          echo 'CXX=/opt/rh/devtoolset-9/root/usr/bin/g++' >> $GITHUB_ENV
#          echo 'PATH=/usr/lib/ccache:'"$PATH" >> $GITHUB_ENV
#          echo 'PREFIX=/tmp/foedag-install' >> $GITHUB_ENV
#          echo "ADDITIONAL_CMAKE_OPTIONS='-DMY_CXX_WARNING_FLAGS="-W -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Werror -UNDEBUG"'" >> $GITHUB_ENV
#          echo 'RULE_MESSAGES=off' >> $GITHUB_ENV
#          echo 'PATH=/usr/lib/ccache:'"$PATH" >> $GITHUB_ENV
#
#
#      - name: Show shell configuration
#        run: |
#          source /opt/rh/rh-python38/enable
#          env
#          which cmake && cmake --version
#          which make && make --version
#          which python3 && python3 --version
#
#      - name: build
#        shell: bash
#        run: |
#          source /opt/rh/devtoolset-9/enable
#          source /opt/rh/rh-python38/enable
#          echo $PWD
#          mkdir build
#          cd build
#          cmake ./../CMakeLists.txt
#
#      - name: Test IP Generation
#        run: |
#          source /opt/rh/devtoolset-9/enable
#          source /opt/rh/rh-python38/enable
#          python3 ./RapidSilicon/IP/axi_dpram/v1_0/axi_dpram_gen.py --data_width=32 --addr_width=8 --build-name=dpram_wrapper --build
#          tree ./ip_build/rapidsilicon/ip/axi_dpram/ -L 4
#          python3 ./RapidSilicon/IP/axi_ram/v1_0/axi_ram_gen.py --data_width=32 --addr_width=8 --build-name=ram_wrapper --build
#          tree ./ip_build/rapidsilicon/ip/axi_ram/ -L 4
#          python3 ./RapidSilicon/IP/axi_register/v1_0/axi_register_gen.py --data_width=64 --addr_width=32 --build-name=register_wrapper --build
#          tree ./ip_build/rapidsilicon/ip/axi_register/ -L 4
#          python3 ./RapidSilicon/IP/axil_gpio/v1_0/axil_gpio_gen.py --data_width=16 --addr_width=8 --build-name=gpio_wrapper --build
#          tree ./ip_build/rapidsilicon/ip/axil_gpio/ -L 4
#          python3 ./RapidSilicon/IP/axil_uart/v1_0/axil_uart_gen.py --addr_width=8 --rdata_width=32 --build-name=uart_wrapper --build
#          tree ./ip_build/rapidsilicon/ip/axil_uart/ -L 4
